run:
	PROVIDER=deepseek API_KEY= MODEL=deepseek-flash PROMPT="你是什么模型？" go run .

run_qwen:
	PROVIDER=qwen API_KEY= MODEL=qwen-plus PROMPT="你是什么模型？" go run .

run_openai:
	PROVIDER=openai API_KEY= MODEL=gpt5.5 PROMPT="你是什么模型？" go run .

run_claude:
	PROVIDER=claude API_KEY= MODEL=claude-hiku-4-5 PROMPT="你是什么模型？" go run .